#!/usr/bin/env python3
"""Write crmvec-rows-tab.h: tables that one lane reads at the same index, laid
side by side as 32-byte rows, so the vector code reads each lane's row with one
load (rows4) instead of one gather per column. Every value is copied exactly
from the verbatim CORE-MATH tables in the crmvec-*-tab.h headers; nothing is
recomputed. The script re-reads what it wrote and exits non-zero unless every
entry matches its source bit for bit.

    python3 gen-row-tables.py > crmvec-rows-tab.h
"""
import re
import struct
import sys

# (row table, index count, source header, columns as (table, column or None)).
# pow, powf and log1p read the same kind of tables, but were measured slower
# or no faster this way (2026-09-26), so they have no rows here.
ROWS = [
    ("LOG_ROW", 363, "crmvec-log-tab.h", [("LOG_INVERSE", None), ("LOG_INV", 0), ("LOG_INV", 1)]),
    ("LOG10_ROW", 363, "crmvec-log10-tab.h", [("LOG10_INVERSE", None), ("LOG10_INV", 0), ("LOG10_INV", 1)]),
    ("LOG2_ROW1", 33, "crmvec-log2-tab.h", [("LOG2_R1", None), ("LOG2_L1", 0), ("LOG2_L1", 1)]),
    ("LOG2_ROW2", 33, "crmvec-log2-tab.h", [("LOG2_R2", None), ("LOG2_L2", 0), ("LOG2_L2", 1)]),
    ("ASINH_ROW1", 33, "crmvec-asinh-tab.h", [("ASINH_R1", None), ("ASINH_L1", 0), ("ASINH_L1", 1)]),
    ("ASINH_ROW2", 33, "crmvec-asinh-tab.h", [("ASINH_R2", None), ("ASINH_L2", 0), ("ASINH_L2", 1)]),
    ("ATANH_ROW1", 33, "crmvec-atanh-tab.h", [("ATANH_R1", None), ("ATANH_L1", 0), ("ATANH_L1", 1)]),
    ("ATANH_ROW2", 33, "crmvec-atanh-tab.h", [("ATANH_R2", None), ("ATANH_L2", 0), ("ATANH_L2", 1)]),
]
# integer tables read at one index: log2's B[i] as a 2-column row (rows2), and
# atan's C0, C1, C2 as a 4-column row, the last 0 (rows4)
INT_ROWS = [("LOG2_B", 32, "crmvec-log2-tab.h", ["LOG2_B0", "LOG2_B1"]),
            ("ATAN_C", 31, "crmvec-atan-tab.h", ["ATAN_C0", "ATAN_C1", "ATAN_C2"])]

DECL = re.compile(r"static\s+const\s+(double|long long)\s+(\w+)\s*((?:\[\d+\])+)\s*(?:__attribute__\(\(\w+\(\d+\)\)\))?\s*=\s*\{(.*?)\}\s*;", re.S)
HEX = re.compile(r"^[-+]?0x[0-9a-fA-F]*\.?[0-9a-fA-F]*p[-+]?\d+$")
DEC = re.compile(r"^[-+]?\d+(\.\d*)?([eE][-+]?\d+)?$")   # e.g. a bare 0; C and Python both round these correctly
INT = re.compile(r"^[-+]?\d+(LL)?$")


def bits(v):
    return struct.unpack("<Q", struct.pack("<d", v))[0]


def tables(path):
    src = re.sub(r"/\*.*?\*/", "", open(path).read(), flags=re.S)
    src = re.sub(r"//[^\n]*", "", src)
    out = {}
    for ctype, name, dims, body in DECL.findall(src):
        shape = [int(d) for d in re.findall(r"\d+", dims)]
        toks = [t.strip() for t in body.replace("{", ",").replace("}", ",").split(",") if t.strip()]
        vals = []
        for t in toks:
            if ctype == "double":
                if HEX.match(t):
                    vals.append(float.fromhex(t))
                elif DEC.match(t):
                    vals.append(float(t))
                else:
                    sys.exit(f"{path}: {name}: not a number: {t!r}")
            else:
                if not INT.match(t):
                    sys.exit(f"{path}: {name}: not an integer: {t!r}")
                vals.append(int(t.removesuffix("LL")))
        n = 1
        for d in shape:
            n *= d
        if len(vals) != n:
            sys.exit(f"{path}: {name}: {len(vals)} values for shape {shape}")
        out[name] = (shape, vals)
    return out


def column(tabs, name, col, i):
    shape, vals = tabs[name]
    return vals[i] if col is None else vals[i * shape[1] + col]


def main():
    cache = {}
    def get(path):
        if path not in cache:
            cache[path] = tables(path)
        return cache[path]

    lines = ["/* generated by gen-row-tables.py from the verbatim CORE-MATH tables named",
             "   below (do not edit): tables one lane reads at the same index, side by side,",
             "   one 32-byte row per index (the fourth column is 0), so rows4 reads a lane's",
             "   entries with one load. The same values, bit for bit. */"]
    expect = {}
    for name, n, path, cols in ROWS:
        tabs = get(path)
        for t, _ in cols:
            if len(tabs[t][1]) < n or tabs[t][0][0] != n:
                sys.exit(f"{path}: {t} has {tabs[t][0][0]} rows, not {n}")
        rows = [[column(tabs, t, c, i) for t, c in cols] + [0.0] for i in range(n)]
        expect[name] = rows
        desc = ", ".join(t if c is None else f"{t}[i][{c}]" for t, c in cols)
        lines.append(f"/* {name}[i] = {{{desc}, 0}}, from {path} */")
        lines.append(f"static const double {name}[{n}][4] __attribute__((aligned(32))) = {{")
        for r in rows:
            lines.append("  {" + ", ".join(v.hex() for v in r) + "},")
        lines.append("};")
    for name, n, path, cols in INT_ROWS:
        tabs = get(path)
        for t in cols:
            if tabs[t][0] != [n]:
                sys.exit(f"{path}: {t} has shape {tabs[t][0]}, not [{n}]")
        width = 2 if len(cols) == 2 else 4
        rows = [[tabs[t][1][i] for t in cols] + [0] * (width - len(cols)) for i in range(n)]
        expect[name] = rows
        pad = ", 0" * (width - len(cols))
        lines.append(f"/* {name}[i] = {{{', '.join(cols)}{pad}}}, from {path} */")
        lines.append(f"static const long long {name}[{n}][{width}] __attribute__((aligned({8 * width}))) = {{")
        for r in rows:
            lines.append("  {" + ", ".join(f"{v}LL" for v in r) + "},")
        lines.append("};")
    text = "\n".join(lines) + "\n"

    # re-read what is about to be written and compare bit for bit
    got = {}
    for ctype, name, dims, body in DECL.findall(re.sub(r"/\*.*?\*/", "", text, flags=re.S)):
        toks = [t.strip() for t in body.replace("{", ",").replace("}", ",").split(",") if t.strip()]
        got[name] = [float.fromhex(t) if ctype == "double" else int(t.removesuffix("LL")) for t in toks]
    for name, rows in expect.items():
        flat = [v for r in rows for v in r]
        same = len(got.get(name, [])) == len(flat) and all(
            (bits(a) == bits(b)) if isinstance(a, float) else a == b for a, b in zip(got[name], flat))
        if not same:
            sys.exit(f"{name}: written table does not read back identical")
    sys.stdout.write(text)
    print(f"{len(expect)} row tables, every entry read back identical", file=sys.stderr)


if __name__ == "__main__":
    main()
