#!/usr/bin/env python3
# Generates crmvec-erff-t2-tab.h, the table of erff's float-lane path (2026-10-02; openpocl's
# harness/tiers/gen-erf-tables.py, the same values): for r = k/128, k = 0..NK-1, erf(r) and
# S(r) = 2/sqrt(pi) exp(-r^2) as float pairs (each part rounded to double, then to float, as that
# generator did), from mpmath at 200 bits. Needs mpmath.  python3 gen-erff-t2-tab.py > crmvec-erff-t2-tab.h
import struct
from mpmath import mp, mpf, erf, exp, sqrt, pi
mp.prec = 200
NK = 505
def f32(v):
    return struct.unpack("f", struct.pack("f", float(v)))[0]
def lit(v):
    if v == 0:
        return "0x0p+0f"
    m, e = float(v).hex().split("p")
    return "%sp%sf" % (m.rstrip("0").rstrip("."), e)
print("/* crmvec-erff-t2-tab.h: generated by gen-erff-t2-tab.py -- do not edit. ERFF_T2[k] = {erf hi, erf lo,")
print("   S hi, S lo} at r = k/128, S = 2/sqrt(pi) exp(-r^2). */")
print("#define ERFF_T2_NK %d" % NK)
print("static const float ERFF_T2[ERFF_T2_NK][4] __attribute__((aligned(16))) = {")
for k in range(NK):
    r = mpf(k) / 128
    E = erf(r); S = 2 / sqrt(pi) * exp(-r * r)
    eh = f32(E); el = f32(E - mpf(eh)); sh = f32(S); sl = f32(S - mpf(sh))
    print("  {" + ", ".join(lit(v) for v in (eh, el, sh, sl)) + "},")
print("};")
