#!/usr/bin/env python3
"""The poles of tan used by tan-poles.c: the double nearest (k + 1/2) pi for
k = 0..399 and 800 random k with (k + 1/2) pi < 2^31. Writes tan-poles.h."""
import mpmath, random
mpmath.mp.prec = 200
random.seed(20260926)
ks = list(range(0, 400)) + [random.randrange(400, 683565275) for _ in range(800)]
with open("tan-poles.h", "w") as f:
    f.write("/* generated by gen-tan-poles.py: do not edit */\n")
    f.write("static const double POLES[%d] = {\n" % len(ks))
    f.write(",\n".join(float((k + mpmath.mpf(1) / 2) * mpmath.pi).hex() for k in ks))
    f.write("};\n")
