#!/usr/bin/env python3
# Generates crmvec-erfcf-t2-tab.h, the table of erfcf's float-lane path (2026-10-02; openpocl's
# harness/tiers/gen-erfc-tables.py, the same values): for r = k/128, k = 0..NK-1, erfc(r) and
# S(r) = 2/sqrt(pi) exp(-r^2) as float pairs (each part rounded to double, then to float, as that
# generator did), from mpmath at 200 bits; from k = 960 (r = 7.5) on, both scaled by 2^64, so that no part
# is subnormal and a flush-to-zero caller loses nothing (2026-10-02). Needs mpmath.  python3 gen-erfcf-t2-tab.py > crmvec-erfcf-t2-tab.h
import struct
from mpmath import mp, mpf, erfc, exp, sqrt, pi
mp.prec = 200
NK = 1177            # r up to 9.1875 (k = 1176): beyond, erfc is below the smallest normal float
KS = 960             # from r = 7.5 the rows are scaled by 2^64 (the caller scales the result back)
def f32(v):
    return struct.unpack("f", struct.pack("f", float(v)))[0]
def lit(v):
    if v == 0:
        return "0x0p+0f"
    m, e = float(v).hex().split("p")
    return "%sp%sf" % (m.rstrip("0").rstrip("."), e)
print("/* crmvec-erfcf-t2-tab.h: generated by gen-erfcf-t2-tab.py -- do not edit. ERFCF_T2[k] = {erfc hi, erfc lo,")
print("   S hi, S lo} at r = k/128, S = 2/sqrt(pi) exp(-r^2); rows from ERFCF_T2_KS = 960 (r = 7.5) scaled by 2^64. */")
print("#define ERFCF_T2_KS 960")
print("#define ERFCF_T2_NK %d" % NK)
print("static const float ERFCF_T2[ERFCF_T2_NK][4] __attribute__((aligned(16))) = {")
for k in range(NK):
    r = mpf(k) / 128
    E = erfc(r); S = 2 / sqrt(pi) * exp(-r * r)
    if k >= KS:
        E *= mpf(2) ** 64; S *= mpf(2) ** 64
    eh = f32(E); el = f32(E - mpf(eh)); sh = f32(S); sl = f32(S - mpf(sh))
    print("  {" + ", ".join(lit(v) for v in (eh, el, sh, sl)) + "},")
print("};")
