#!/usr/bin/env python3
# Generates crmvec-pio2.h: for each float exponent with |x| >= 2^28, the
# value T_E = (2^E * 2/pi) mod 4 in four 28-bit pieces (bits 2^1..2^-26,
# 2^-27..2^-54, 2^-55..2^-82, 2^-83..2^-110), so that M * piece is exact in
# double for any 24-bit significand M. x = M * 2^E, E = biased exponent - 150.
from mpmath import mp, mpf, pi, floor
mp.prec = 600
rows = []
for eb in range(155, 255):                 # |x| in [2^28, 2^128)
    E = eb - 150
    t = (mpf(2) ** E * 2 / pi) % 4
    parts = []
    for j in range(4):
        scale = mpf(2) ** (26 + 28 * j)
        c = floor(t * scale) / scale
        parts.append(c); t -= c
    for c in parts:
        assert float(c) == c                # each piece exact in double
    rows.append("  {%s}, /* e %d */" % (", ".join(float(c).hex() for c in parts), eb))
print("/* generated by gen-pio2-table.py: (2^E * 2/pi) mod 4, E = biased exponent - 150 */")
print("static const double PIO2_TAB[100][4] = {")
print("\n".join(rows))
print("};")
