#!/usr/bin/env python3
"""Write crmvec-sleef-aliases.h: for every name in sleef-gnuabi-aarch64.txt
that is another spelling of a function crmvec defines (SLEEF's _u35 and
fast*_u3500 variants, glibc's __*_finite), an alias line; AN(...) for the
AdvSIMD names (crmvec-aarch64.c), AS(...) for SVE (crmvec-sve.c). Fails if
a name maps to no crmvec function. `make sleef-exports` then checks the
built library against the same list."""
import re, sys, os
D = os.path.dirname(os.path.abspath(__file__))
names = [l.strip() for l in open(os.path.join(D, 'sleef-gnuabi-aarch64.txt')) if l.strip() and not l.startswith('#')]
# the functions crmvec defines, by shape, read from the two lists
fns = {}
for m in re.finditer(r'\b([FD][12])\((\w+)\)', open(os.path.join(D, 'crmvec-functions.h')).read()):
    fns[m.group(2)] = m.group(1)[1]                      # '1' or '2' arguments
for m in re.finditer(r'\b[LS]([DF])(1|2|3|I|N|P|PP)\((\w+),', open(os.path.join(D, 'crmvec-lanes.h')).read()):
    fns[m.group(3)] = m.group(2)
pat = re.compile(r'^_ZGV([ns])([NM])(\d+|x)((?:v|l\d+)+)_(\w+)$')
norm = re.compile(r'^(?:__)?(?:fast)?([a-z0-9]+?)(?:_finite)?(?:_u35|_u3500)?$')
out, bad, direct = [], [], 0
for s in names:
    m = pat.match(s)
    if not m: bad.append(f'{s}: not a vector-ABI name'); continue
    isa, mask, vlen, params, fname = m.groups()
    b = norm.match(fname)
    base = b.group(1) if b else None
    if base not in fns: bad.append(f'{s}: {fname} -> {base}, not a crmvec function'); continue
    pre = f'_ZGV{isa}{mask}{vlen}{params}_'
    if fname == base: direct += 1; continue
    out.append(f'{"AN" if isa == "n" else "AS"}({pre}, {fname}, {base})')
if bad:
    print('\n'.join(bad), file=sys.stderr); sys.exit(1)
hdr = os.path.join(D, 'crmvec-sleef-aliases.h')
text = ('/* Generated by gen-sleef-aliases.py from sleef-gnuabi-aarch64.txt; do not edit.\n'
        f'   {len(names)} SLEEF names: {direct} defined directly, {len(out)} aliases here. */\n'
        '#ifndef AN\n#define AN(pre, alias, base)\n#endif\n#ifndef AS\n#define AS(pre, alias, base)\n#endif\n'
        + '\n'.join(out) + '\n#undef AN\n#undef AS\n')
check = '--check' in sys.argv
if check:
    same = os.path.exists(hdr) and open(hdr).read() == text
    print(f'crmvec-sleef-aliases.h {"regenerates identically" if same else "DIFFERS from its generator"}')
    sys.exit(0 if same else 1)
open(hdr, 'w').write(text)
print(f'{len(names)} names: {direct} direct, {len(out)} aliases')
