#!/usr/bin/env python3
"""Tables and polynomials for log_core_d's table-size experiment.

ln x = k ln2 + ln c_i + log1p(z/c_i - 1), where z is x scaled into
[OFF, 2 OFF) by an integer subtraction and i is the top b bits of
(bits(x) - OFF) below the exponent field (glibc's layout). OFF is chosen so
that bits(1.0) is the centre of interval i0, whose entry is exactly
invc = 1, logc = 0: for x near 1 the sum then has no cancellation.
invc[i] = RN(1/centre), logc[i] = RN(-ln invc[i]) (mpmath). p ~ log1p on
the widest |r| of the table, from Sollya: the lowest degree with relative
error <= 2^-TARGET. Writes crmvec-log-var.h.

  python3 gen-log-variants.py [TARGET]       (default 39)
"""
import math, struct, subprocess, sys
import mpmath

TARGET = int(sys.argv[1]) if len(sys.argv) > 1 else 39
mpmath.mp.prec = 200
ONE = 0x3ff0000000000000
d2i = lambda d: struct.unpack("<Q", struct.pack("<d", d))[0]
i2d = lambda i: struct.unpack("<d", struct.pack("<Q", i))[0]


def minimax(lo, hi, d):
    s = (f"prec=300; display=hexadecimal; p = fpminimax(log1p(x), [|1,...,{d}|], [|D...|], [{lo!r};{hi!r}], relative);"
         f" for i from 1 to {d} do print(coeff(p, i)); display=decimal;"
         f" print(dirtyinfnorm(p/log1p(x)-1, [{lo!r};{hi!r}]));")
    out = subprocess.run(["sollya"], input=s, capture_output=True, text=True).stdout.splitlines()
    cs = [w.strip() for w in out if w.strip().startswith(("0x", "-0x"))]
    assert len(cs) == d, out
    return cs, float(out[-1])


lines = [f"/* generated by gen-log-variants.py {TARGET}: do not edit */"]
for b in range(3, 9):
    N, W = 1 << b, 1 << (52 - b)
    i0 = round((ONE - 0x3fe6955500000000) / W - 0.5)      # glibc's offset, moved so 1.0 is a centre
    OFF = ONE - (2 * i0 + 1) * W // 2
    invc, logc, rlo, rhi = [], [], 0.0, 0.0
    for i in range(N):
        a, e = i2d(OFF + i * W), i2d(OFF + (i + 1) * W)
        if i == i0:
            ic, lc = 1.0, 0.0
        else:
            ic = float(1 / ((mpmath.mpf(a) + mpmath.mpf(e)) / 2))
            lc = float(-mpmath.log(mpmath.mpf(ic)))
        invc.append(ic); logc.append(lc)
        rlo = min(rlo, float(mpmath.mpf(a) * ic - 1)); rhi = max(rhi, float(mpmath.mpf(e) * ic - 1))
    rlo, rhi = rlo * 1.001, rhi * 1.001
    for d in range(3, 14):
        cs, err = minimax(rlo, rhi, d)
        if err <= 2.0 ** -TARGET:
            break
    pad = [0.0] * (max(N, 4) - N)
    lines.append(f"/* N={N}: r in [{rlo:.4g}, {rhi:.4g}], degree {d}, relative error 2^{math.log2(err):.1f}; 1.0 is the centre of entry {i0} */")
    lines.append(f"#define LOG_OFF_{b} 0x{OFF:016x}LL")
    lines.append(f"#define LOG_DEG_{b} {d}")
    lines.append(f"static const double LOG_P_{b}[{d}] = {{{', '.join(cs)}}};   /* r^1 .. r^{d} */")
    lines.append(f"static const double LOG_IC_{b}[{max(N, 4)}] __attribute__((aligned(32))) = {{" + ", ".join(v.hex() for v in invc + pad) + "};")
    lines.append(f"static const double LOG_LC_{b}[{max(N, 4)}] __attribute__((aligned(32))) = {{" + ", ".join(v.hex() for v in logc + pad) + "};")
    lines.append(f"static const double LOG_ROW_{b}[{2 * N}] __attribute__((aligned(32))) = {{"
                 + ", ".join(f"{u.hex()}, {v.hex()}" for u, v in zip(invc, logc)) + "};   /* invc, logc pairs */")
    print(f"N={N:4d}: r in [{rlo:.4g}, {rhi:.4g}], degree {d:2d}, error 2^{math.log2(err):.1f}", file=sys.stderr)
open("crmvec-log-var.h", "w").write("\n".join(lines) + "\n")
