#!/usr/bin/env python3
"""Tables and polynomials for exp2_core's table-size experiment.

For each table size N = 2^b (b = 0..8): 2^t = 2^e * T[j] * 2^r with
t = e + j/N + r, |r| <= 1/(2N). T[j] = 2^(j/N) rounded to double (mpmath),
and p(r) ~ 2^r the lowest-degree Sollya fpminimax polynomial whose
relative error is at most 2^-TARGET. Writes crmvec-exp2-var.h.

  python3 gen-exp2-variants.py [TARGET]      (default 39)
"""
import math, subprocess, sys
import mpmath

TARGET = int(sys.argv[1]) if len(sys.argv) > 1 else 39
mpmath.mp.prec = 200


def minimax(N, d):
    s = (f"prec=300; display=hexadecimal; p = fpminimax(2^x, {d}, [|D...|], [-1/(2*{N});1/(2*{N})], relative);"
         f" for i from 0 to {d} do print(coeff(p, i)); display=decimal;"
         f" print(dirtyinfnorm(p/2^x-1, [-1/(2*{N});1/(2*{N})]));")
    out = subprocess.run(["sollya"], input=s, capture_output=True, text=True).stdout.splitlines()
    cs = [w.strip() for w in out if w.strip().startswith(("0x", "-0x"))]
    err = float(out[-1])
    assert len(cs) == d + 1, out
    return cs, err


lines = [f"/* generated by gen-exp2-variants.py {TARGET}: do not edit */"]
for b in range(0, 9):
    N = 1 << b
    for d in range(2, 12):
        cs, err = minimax(N, d)
        if err <= 2.0 ** -TARGET:
            break
    lines.append(f"/* N={N}: degree {d}, relative error 2^{math.log2(err):.1f} on |r| <= 1/{2 * N} */")
    lines.append(f"#define EXP2_DEG_{b} {d}")
    lines.append(f"static const double EXP2_P_{b}[{d + 1}] = {{{', '.join(cs)}}};")
    tab = [float(mpmath.power(2, mpmath.mpf(j) / N)) for j in range(N)]
    tab += [0.0] * (max(N, 4) - N)   # padded: the permute lookup loads 4 at a time
    lines.append(f"static const double EXP2_T_{b}[{max(N, 4)}] __attribute__((aligned(32))) = {{"
                 + ", ".join(t.hex() for t in tab) + "};")
    print(f"N={N:4d}: degree {d:2d}, error 2^{math.log2(err):.1f}", file=sys.stderr)
open("crmvec-exp2-var.h", "w").write("\n".join(lines) + "\n")
