#!/usr/bin/env python3
"""Write crmvec-rename.h: every AVX2 entry point name of crmvec-functions.h
(_ZGVdN8v_expf, ...) renamed to the internal crvi_<name>, so that crmvec.c's
vector code is defined under the internal name and the exported name belongs
to the guard at the end of crmvec.c (the rounding mode; on x86, where the
exported name is the AVX entry point's alias since 2026-09-29, the CPU too).
`--check`: exit 1 unless the header regenerates identically. Added
2026-09-27."""
import os, re, sys
D = os.path.dirname(os.path.abspath(__file__))
pre = {"F1": "_ZGVdN8v_", "D1": "_ZGVdN4v_", "F2": "_ZGVdN8vv_", "D2": "_ZGVdN4vv_"}
lines = [f"#define {pre[m.group(1)]}{m.group(2)} crvi_{m.group(2)}"
         for m in re.finditer(r"\b([FD][12])\((\w+)\)", open(os.path.join(D, "crmvec-functions.h")).read())]
text = ("/* Generated by gen-guard.py from crmvec-functions.h; do not edit.\n"
        f"   The {len(lines)} AVX2 entry points, renamed to their internal names. */\n" + "\n".join(lines) + "\n")
h = os.path.join(D, "crmvec-rename.h")
if "--check" in sys.argv:
    ok = os.path.exists(h) and open(h).read() == text
    print(f"crmvec-rename.h {'regenerates identically' if ok else 'DIFFERS from its generator'}"); sys.exit(0 if ok else 1)
open(h, "w").write(text); print(f"{len(lines)} names")
