#!/bin/bash
# mkdispatch.sh: the pieces of the dispatching libcrpreload.so (2026-10-01),
# in objd/. Both builds go into one library: the generic objects (obj/) as
# they are, and the x86-64-v3 ones (objv3/) with every global symbol they
# define renamed X -> X_v3, references included, so the two never meet.
# The wrappers (crpreload.o of each build) get their exports renamed to
# crp_g_<name> and crp_v3_<name>, and objd/dispatch.S makes each libm name
# a trampoline to the v3 wrapper on a CPU with AVX2 and FMA (objd/pick.c's
# constructor decides), the generic one otherwise. The results are the same either way (CORE-MATH is
# correctly rounded; crpreload-check runs both builds); the v3 one inlines
# its fused multiply-adds instead of calling glibc's fma.
set -euo pipefail
cd "$(dirname "$0")"
D=objd; rm -rf $D; mkdir -p $D/v3
# the list from make, run without the parent make's flags, and only its object
# names: under Debian's nested build the output also carried "Entering
# directory" lines, which nm then tried to open
V3=$(env -u MAKEFLAGS -u MFLAGS -u MAKELEVEL make -s --no-print-directory print-objects-v3 | tr ' ' '\n' | grep -E '^objv3/.+\.o$')
[ -n "$V3" ] || { echo "mkdispatch: no v3 objects listed"; exit 1; }
nm --defined-only -g $V3 | awk 'NF == 3 { print $3, $3 "_v3" }' | sort -u > $D/v3.map
for o in $V3; do objcopy --redefine-syms=$D/v3.map "$o" "$D/v3/$(echo "$o" | tr / _)"; done
nm --defined-only -g obj/crpreload.o | awk 'NF == 3 && $2 ~ /^[TW]$/ { print $3 }' | sort -u > $D/exports
cmp -s $D/exports <(nm --defined-only -g objv3/crpreload.o | awk 'NF == 3 && $2 ~ /^[TW]$/ { print $3 }' | sort -u) ||
  { echo "mkdispatch: the two builds export different names"; exit 1; }
awk '{ print $1, "crp_g_" $1 }' $D/exports > $D/g.map
objcopy --redefine-syms=$D/g.map obj/crpreload.o $D/crpreload-g.o
{ awk '{ print $1, "crp_v3_" $1 }' $D/exports; cat $D/v3.map; } > $D/v3w.map
objcopy --redefine-syms=$D/v3w.map objv3/crpreload.o $D/crpreload-v3.o
# Not ifuncs (2026-10-01): a preloaded library is relocated after the
# libraries that call it, so glibc's loader printed "Relink ... for IFUNC
# symbol" for every name a library used (47 for FLIRT), though the results
# were right. Instead each name is a three-instruction trampoline that tests
# a flag a constructor sets and jumps on; before the constructor runs, the
# flag is 0 and the generic code answers, which is right too.
{ echo "/* objd/dispatch.S: generated by mkdispatch.sh; do not edit */"
  echo "        .section .note.GNU-stack,\"\",@progbits"
  echo "        .text"
  while read -r n; do
    echo "        .hidden crp_g_$n"; echo "        .hidden crp_v3_$n"
    echo "        .globl $n"; echo "        .type $n, @function"; echo "        .p2align 4"
    echo "$n:"; echo "        cmpb \$0, crp_have_v3(%rip)"; echo "        jne crp_v3_$n"; echo "        jmp crp_g_$n"
    echo "        .size $n, .-$n"
  done < $D/exports; } > $D/dispatch.S
{ echo "/* objd/pick.c: generated by mkdispatch.sh; do not edit */"
  echo "__attribute__((visibility(\"hidden\"))) unsigned char crp_have_v3;"
  echo "__attribute__((constructor)) static void crp_pick(void)"
  echo "{ __builtin_cpu_init(); crp_have_v3 = __builtin_cpu_supports(\"avx2\") && __builtin_cpu_supports(\"fma\"); }"; } > $D/pick.c
{ echo "{ global:"; sed 's/$/;/' $D/exports; echo "local: *; };"; } > $D/exports.map   # only the libm names leave the library
echo "objd: $(wc -l < $D/exports) names dispatched, $(wc -l < $D/v3.map) v3 symbols renamed"
