"""gen-log2d-tables.py -> log2d-tables.h (2026-10-01): tables for tierd-log2.c's and tierd-log.c's LOGD_FAST=3 (b = 2, 10, e), log_b x =
(k log_b 2 + log_b c) + r P(r), r = z/c - 1 in one rounding, P(r) = log_b(1 + r)/r.
Next to 1 the sum cancels: log128-tables.h's grid holds 1 a third of the way up its subinterval ([0.9987, 1.0052]),
so the neighbour below cancels 2.5 times and log2 reached 3 ulp at 0x1.ff549bca5b66dp-1. Here:
  - OFF centres 1 in its subinterval ([0.9974, 1.0026]; the neighbours cancel at most 2 times);
  - each 1/c is moved (by multiples of 2^-41, under 2^-28 relative) until -log_b(1/c) is within 2^-12 ulp of a
    double, so the table adds no error (log128's 1/c were picked that way for ln, not for log2 or log10);
  - c = 1 on the subinterval holding 1, where r = z - 1 exactly.
P's coefficients: (1/ln b)(1 + r p(r)) with log128's near-minimax p of degree 5 (|r| <= 0.0055), rounded to double."""
import struct, mpmath as mp
mp.mp.prec = 160
OFF = 0x3fe68aaaaaaaaaab   # bits(1 - (2/3) 2^-8) - 75 * 2^45
def d(bits): return struct.unpack("<d", struct.pack("<Q", bits))[0]
def ulp(v):
    e = mp.floor(mp.log(abs(v), 2)); return mp.mpf(2) ** (e - 52)
one = (0x3ff0000000000000 - OFF) >> 45
lo1, hi1 = d(OFF + one * (1 << 45)), d(OFF + (one + 1) * (1 << 45))
pc = ["-0x1.0000000000003p-1", "0x1.555555555555bp-2", "-0x1.fffffffc8f9bfp-3", "0x1.99999996a6fa7p-3", "-0x1.5558cd81038dep-3", "0x1.2495548ef3363p-3"]
out = ["/* log2d-tables.h: generated by gen-log2d-tables.py -- do not edit */",
       "#define LOG2D_OFF 0x%xLL   /* z in [%.6f, %.6f); the subinterval holding 1 (%d): [%.6f, %.6f] */" % (OFF, d(OFF), d(OFF + (1 << 52)) if False else 2 * d(OFF), one, lo1, hi1)]
rmax = 0
for name, b in (("LOG2D", 2), ("LOG10D", 10), ("LOGED", mp.e)):
    rows, worst = [], 0
    lb = mp.log(b)
    for j in range(128):
        lo, hi = d(OFF + j * (1 << 45)), d(OFF + (j + 1) * (1 << 45)) if j < 127 else 2 * d(OFF)
        if j == one:
            ic, lc = 1.0, 0.0
        else:
            c = mp.sqrt(mp.mpf(lo) * hi)
            base = float(mp.nint(mp.mpf(1) / c * 2 ** 41)) / 2 ** 41
            best = None
            for t in range(0, 20000):
                for s in ((t, -t) if t else (0,)):
                    ic = base + s * 2.0 ** -41
                    v = -mp.log(mp.mpf(ic)) / lb
                    err = abs(v - mp.mpf(float(v))) / ulp(v)
                    if best is None or err < best[0]: best = (err, ic, float(v))
                if best[0] < mp.mpf(2) ** -12: break
            err, ic, lc = best
            worst = max(worst, err)
        rmax = max(rmax, abs(lo * ic - 1), abs(hi * ic - 1))
        rows.append("{%s, %s}" % (ic.hex(), lc.hex()))
    out.append("static const double %s_ROWS[128][2] __attribute__((aligned(16))) = {%s};   /* table error at most %.2g ulp */" % (name, ", ".join(rows), float(worst)))
    k = 1 / lb
    out.append("#define %s_P %s" % (name, ", ".join(float(c).hex() for c in [k] + [k * mp.mpf(float.fromhex(c)) for c in pc])))
out.append("/* |r| <= %.5f on every subinterval (P is fitted to 0.0055) */" % rmax)
open("log2d-tables.h", "w").write("\n".join(out) + "\n")
print("one =", one, lo1, hi1, "rmax", rmax)
for l in out:
    if "ulp */" in l: print(l[-40:])
