"""gen-exp32-tables.py: the constants of tierd-exp.c (2026-10-01), written
to exp32-tables.h (generated: do not edit): 2^(j/32), j = 0..31, as
double-double pairs, and ln 2/32 in three parts (the first of 36
significant bits, so k C1 is exact for |k| < 2^17)."""
import mpmath as mp
mp.mp.prec = 300
def d(v): return float(v)
hi = []; lo = []
for j in range(32):
    v = mp.power(2, mp.mpf(j) / 32); h = d(v); l = d(v - mp.mpf(h)); hi.append(h); lo.append(l)
C = mp.log(2) / 32
e = mp.floor(mp.log(C, 2))
C1 = mp.nint(C * mp.power(2, 35 - e)) / mp.power(2, 35 - e)    # 36 significant bits
C2 = d(C - C1); C3 = d(C - C1 - mp.mpf(C2))
out = ["/* exp32-tables.h: generated by gen-exp32-tables.py -- do not edit */",
       "static const double EXP32_HI[32] = {" + ", ".join(float(v).hex() for v in hi) + "};",
       "static const double EXP32_LO[32] = {" + ", ".join(float(v).hex() for v in lo) + "};",
       f"#define EXP32_C1 {d(C1).hex()}", f"#define EXP32_C2 {C2.hex()}", f"#define EXP32_C3 {C3.hex()}",
       f"#define EXP32_INV {d(32 / mp.log(2)).hex()}"]
open("exp32-tables.h", "w").write("\n".join(out) + "\n")
print("\n".join(out[3:]))
