"""gen-erf-tables.py: the tables of tier-erff.c (2026-10-01), written to
erf-tables.h (generated: do not edit). For r = k/128, k = 0..NK-1:
erf(r) and S(r) = 2/sqrt(pi) exp(-r^2) as float pairs (hi = the float
nearest, lo = the float nearest the rest), from mpmath at 200 bits.
NK covers r up to 3.9375; erf(x) rounds to 1 from x = 3.9192 on."""
import mpmath as mp
import numpy as np
mp.mp.prec = 200
NK = 505
f32 = lambda v: float(np.float32(float(v)))
def lit(v):
    if v == 0: return "0x0p+0f"
    m, e = float(v).hex().split("p")
    return f"{m.rstrip('0').rstrip('.')}p{e}f"
rows = []
for k in range(NK):
    r = mp.mpf(k) / 128
    E = mp.erf(r); S = 2 / mp.sqrt(mp.pi) * mp.exp(-r * r)
    eh = f32(E); el = f32(E - mp.mpf(eh)); sh = f32(S); sl = f32(S - mp.mpf(sh))
    rows.append((eh, el, sh, sl))
out = ["/* erf-tables.h: generated by gen-erf-tables.py -- do not edit. ERF_ROWS[k] = {erf hi, erf lo, S hi, S lo}",
       "   at r = k/128, S = 2/sqrt(pi) exp(-r^2). */",
       f"#define ERF_NK {NK}",
       "static const float ERF_ROWS[ERF_NK][4] __attribute__((aligned(16))) = {"]
for row in rows:
    out.append("  {" + ", ".join(lit(v) for v in row) + "},")
out.append("};")
open("erf-tables.h", "w").write("\n".join(out) + "\n")
print("wrote erf-tables.h,", NK, "rows")
