"""gen-log128-tables.py: the tables of tierd-log.c (2026-10-01), written to
log128-tables.h (generated: do not edit). glibc's reduction: tmp = ix - OFF,
OFF = 0x3fe6955500000000, i = bits 51-45 of tmp, z = x scaled into
[OFF, 2 OFF). Subinterval i is z in [OFF + i 2^45, OFF + (i+1) 2^45) as bit
patterns; c_i its midpoint, ic_i = 1/c_i rounded to 32 significant bits,
LOGC_i = -log(ic_i) as a double-double; the subinterval holding 1 gets
ic = 1, LOGC = 0. Also ln 2 in three parts (L1 of 42 bits: k L1 exact for
|k| < 2^11)."""
import mpmath as mp, struct
mp.mp.prec = 300
OFF = 0x3fe6955500000000
def dbl(bits): return struct.unpack("<d", struct.pack("<Q", bits))[0]
ic = []; lch = []; lcl = []
for i in range(128):
    z0 = dbl(OFF + i * (1 << 45)); z1 = dbl(OFF + (i + 1) * (1 << 45))
    if z0 <= 1.0 < z1:
        ic.append(1.0); lch.append(0.0); lcl.append(0.0); one = i; continue
    c = (mp.mpf(z0) + mp.mpf(z1)) / 2
    e = mp.floor(mp.log(1 / c, 2))
    v = float(mp.nint(mp.power(2, 31 - e) / c) / mp.power(2, 31 - e))   # 32 significant bits
    L = -mp.log(mp.mpf(v)); h = float(L); l = float(L - mp.mpf(h))
    ic.append(v); lch.append(h); lcl.append(l)
L = mp.log(2); e = mp.floor(mp.log(L, 2))
L1 = float(mp.floor(L * mp.power(2, 41 - e)) / mp.power(2, 41 - e)); L2 = float(L - mp.mpf(L1)); L3 = float(L - mp.mpf(L1) - mp.mpf(L2))
out = ["/* log128-tables.h: generated by gen-log128-tables.py -- do not edit */",
       f"#define LOG128_ONE {one}   /* the subinterval holding 1 */",
       "static const double LOG128_IC[128] = {" + ", ".join(float(v).hex() for v in ic) + "};",
       "static const double LOG128_LCH[128] = {" + ", ".join(float(v).hex() for v in lch) + "};",
       "static const double LOG128_LCL[128] = {" + ", ".join(float(v).hex() for v in lcl) + "};",
       "/* {IC, LCH} side by side, for tier 1's 128-bit row loads (tierd-poly.h's rows2_pd) */",
       "static const double LOG128_ROWS[128][2] __attribute__((aligned(16))) = {" + ", ".join("{%s, %s}" % (float(a).hex(), float(b).hex()) for a, b in zip(ic, lch)) + "};",
       f"#define LOG128_L1 {L1.hex()}", f"#define LOG128_L2 {L2.hex()}", f"#define LOG128_L3 {L3.hex()}"]
open("log128-tables.h", "w").write("\n".join(out) + "\n")
print(out[1]); print("\n".join(out[7:]))
