"""gen-erff-pieces.py: piecewise polynomials for a gather-free erff tier 1
(2026-10-01), written to erff-pieces.h (generated: do not edit).
a = |x| in [0, 3.93] in 8 intervals [i/2, (i+1)/2) (the last to 3.93,
where erff rounds to 1 from 3.9192 on), and on each erf(a) = P_i(a - c_i),
c_0 = 0 and c_i the interval's centre otherwise, so a - c_i is exact. P_0
is odd (its even coefficients exactly 0), so tiny a keeps its relative
accuracy. Least squares on Chebyshev nodes of the relative error, in
mpmath; float coefficients; the largest relative error printed, evaluated
in double with the float coefficients, and in float by Horner (as tier 1
does). The coefficient k of all eight intervals forms one row: eight
floats, one _mm256_permutevar8x32_ps each.
  python3 gen-erff-pieces.py DEG"""
import sys
import numpy as np
import mpmath as mp
mp.mp.prec = 120
D = int(sys.argv[1])
f32 = lambda v: float(np.float32(float(v)))
NI = 8
edges = [mp.mpf(i) / 2 for i in range(NI)] + [mp.mpf("3.93")]
rows = [[0.0] * NI for _ in range(D + 1)]
centres = []
k1lo = []
worst_all = 0
for i in range(NI):
    lo, hi = edges[i], edges[i + 1]
    c = mp.mpf(0) if i == 0 else (lo + hi) / 2 if i < NI - 1 else mp.mpf(i) / 2 + mp.mpf(1) / 4
    c = mp.mpf(f32(c))
    centres.append(float(c))
    N = 300
    ts = [((lo + hi) / 2 + (hi - lo) / 2 * mp.cos(mp.pi * (k + mp.mpf(1) / 2) / N)) - c for k in range(N)]
    if i == 0:
        ks = list(range(1, D + 1, 2))            # odd powers only
    else:
        ks = list(range(D + 1))
    A = mp.matrix(N, len(ks)); b = mp.matrix(N, 1)
    for n, t in enumerate(ts):
        v = mp.erf(c + t); w = 1 / v
        for j, k in enumerate(ks): A[n, j] = w * t ** k
        b[n] = w * v
    sol = mp.lu_solve(A.T * A, A.T * b)
    coef = [0.0] * (D + 1)
    for j, k in enumerate(ks): coef[k] = f32(sol[j])
    k1 = ks.index(1)
    k1lo.append(f32(sol[k1] - mp.mpf(coef[1])))   # the linear coefficient's low part: 2/sqrt(pi) is 2^-25 off in float
    for k in range(D + 1): rows[k][i] = coef[k]
    # check in double and in float Horner
    worst_d = worst_f = 0
    for n in range(2001):
        a = lo + (hi - lo) * n / 2000
        if a == 0: continue
        t = float(a - c)
        pd = 0.0
        for k in reversed(range(D + 1)): pd = pd * t + coef[k]
        pf = np.float32(0)
        tf = np.float32(t)
        for k in reversed(range(D + 1)): pf = np.float32(np.float32(pf * tf) + np.float32(coef[k]))
        ex = mp.erf(a)
        worst_d = max(worst_d, abs((pd - ex) / ex)); worst_f = max(worst_f, abs((float(pf) - ex) / ex))
    worst_all = max(worst_all, worst_d)
    print(f"interval {i} [{float(lo)}, {float(hi)}) c={float(c)}: double 2^{float(mp.log(worst_d, 2)):.1f}, float Horner 2^{float(mp.log(worst_f, 2)):.1f}")
lit = lambda v: (float(v).hex().replace("0x0.0p+0", "0x0p+0")) + "f"
out = [f"/* erff-pieces.h: generated by gen-erff-pieces.py {D} -- do not edit. erf(a) = P_i(a - c_i) on [i/2, (i+1)/2),",
       f"   i = min(7, floor(2a)); ERFP_C[i] = c_i; ERFP_K[k][i] = coefficient k of P_i (rows for permutevar8x32);",
       f"   largest relative error with these float coefficients, in double: 2^{float(mp.log(worst_all, 2)):.1f} */",
       f"#define ERFP_DEG {D}",
       "static const float ERFP_C[8] __attribute__((aligned(32))) = {" + ", ".join(lit(v) for v in centres) + "};",
       "/* the linear coefficient's low part (the fit's value minus its float), added by one more FMA */",
       "static const float ERFP_K1LO[8] __attribute__((aligned(32))) = {" + ", ".join(lit(v) for v in k1lo) + "};",
       f"static const float ERFP_K[{D + 1}][8] __attribute__((aligned(32))) = {{"]
for k in range(D + 1):
    out.append("  {" + ", ".join(lit(v) for v in rows[k]) + "},")
out.append("};")
open("erff-pieces.h", "w").write("\n".join(out) + "\n")
print(f"wrote erff-pieces.h, degree {D}, worst 2^{float(mp.log(worst_all, 2)):.1f}")
