"""gen-powf-tables.py: the tables of tier-powf.c (2026-10-01), written to
powf-tables.h (generated: do not edit), after glibc's powf: log2 by 16
subintervals of [OFF, 2 OFF) (OFF = 0x3f330000 as float bits, as logf):
INVC = 1/c rounded to double, LOGC = log2(c) of that rounded c (so r = z INVC - 1
is relative to it); exp2 by 32 entries T[j] = bits of 2^(j/32) minus j << 47,
so adding k << 47 to them scales by 2^(k/32) (glibc's trick). The polynomial
coefficients are near-minimax, fitted here in mpmath on the reduced ranges."""
import mpmath as mp, struct
mp.mp.prec = 200
def fbits(b): return struct.unpack("<f", struct.pack("<I", b))[0]
def dbits(v): return struct.unpack("<Q", struct.pack("<d", v))[0]
OFF = 0x3f330000
invc = []; logc = []; rmax = 0
for i in range(16):
    z0 = fbits(OFF + (i << 19)); z1 = fbits(OFF + ((i + 1) << 19))
    c = (mp.mpf(z0) + mp.mpf(z1)) / 2
    if z0 <= 1.0 < z1: c = mp.mpf(1)       # the subinterval holding 1: r = z - 1 exactly, log2 x relative (pow with large y)
    ic = float(1 / c); invc.append(ic); logc.append(float(-mp.log(mp.mpf(ic), 2)))
    rmax = max(rmax, float(max(abs(z0 * mp.mpf(ic) - 1), abs(z1 * mp.mpf(ic) - 1))))
    if ic == 1.0: print("subinterval", i, "holds 1: c = 1, r in", z0 - 1, z1 - 1)
def fit(f, deg, a, rel):
    N = 300; nodes = [a * mp.cos(mp.pi * (k + mp.mpf(1) / 2) / N) for k in range(N)]
    A = mp.matrix(N, deg + 1); b = mp.matrix(N, 1)
    for i, t in enumerate(nodes):
        w = 1 / abs(rel(t)) if rel(t) != 0 else 1
        for k in range(deg + 1): A[i, k] = w * t ** k
        b[i] = w * f(t)
    c = mp.lu_solve(A.T * A, A.T * b)
    return [float(c[k]) for k in range(deg + 1)]
# log2(1 + r) = r (A0 + A1 r + ... + A4 r^4), relative to log2(1 + r)
A = fit(lambda t: mp.log(1 + t, 2) / t if t != 0 else 1 / mp.log(2), 5, rmax * 1.01, lambda t: mp.mpf(1))
# 2^r = 1 + r (C0 + C1 r + C2 r^2), |r| <= 1/64, relative to 2^r
C = fit(lambda t: (mp.power(2, t) - 1) / t if t != 0 else mp.log(2), 3, 1 / 64 * 1.01, lambda t: mp.mpf(1))
# shorter fits for the 3-ulp budget (2026-10-01, tier-powf.c's POWF_LOW): A of degree 4, C of degree 2
A4 = fit(lambda t: mp.log(1 + t, 2) / t if t != 0 else 1 / mp.log(2), 4, rmax * 1.01, lambda t: mp.mpf(1))
C2 = fit(lambda t: (mp.power(2, t) - 1) / t if t != 0 else mp.log(2), 2, 1 / 64 * 1.01, lambda t: mp.mpf(1))
T = [dbits(float(mp.power(2, mp.mpf(j) / 32))) - (j << 47) for j in range(32)]
out = ["/* powf-tables.h: generated by gen-powf-tables.py -- do not edit */",
       "static const double POWF_INVC[16] = {" + ", ".join(v.hex() for v in invc) + "};",
       "static const double POWF_LOGC[16] = {" + ", ".join(v.hex() for v in logc) + "};",
       "static const double POWF_A[6] = {" + ", ".join(v.hex() for v in A) + "};   /* log2(1 + r) = r (A0 + ... + A5 r^5) */",
       "static const double POWF_C[4] = {" + ", ".join(v.hex() for v in C) + "};   /* 2^r = 1 + r (C0 + ... + C3 r^3) */",
       "static const double POWF_A4[5] = {" + ", ".join(v.hex() for v in A4) + "};   /* degree 4, for POWF_LOW */",
       "static const double POWF_C2[3] = {" + ", ".join(v.hex() for v in C2) + "};   /* degree 2, for POWF_LOW */",
       "static const uint64_t POWF_T[32] = {" + ", ".join(f"0x{v & (2**64 - 1):016x}ULL" for v in T) + "};",
       f"/* |r| <= {rmax:.5f} for the log2 polynomial */"]
open("powf-tables.h", "w").write("\n".join(out) + "\n")
print("\n".join(out[3:]))
# accuracy of the fits
e1 = max(abs(mp.mpf(t) * sum(A[k] * mp.mpf(t) ** k for k in range(6)) / mp.log(1 + mp.mpf(t), 2) - 1) for t in [rmax * (2 * i / 2000 - 1) for i in range(2001)] if t != 0)
e2 = max(abs((1 + mp.mpf(t) * sum(C[k] * mp.mpf(t) ** k for k in range(4))) / mp.power(2, mp.mpf(t)) - 1) for t in [1 / 64 * (2 * i / 2000 - 1) for i in range(2001)])
print(f"log2 poly rel err 2^{float(mp.log(e1, 2)):.1f}, exp2 poly rel err 2^{float(mp.log(e2, 2)):.1f}")
e3 = max(abs(mp.mpf(t) * sum(A4[k] * mp.mpf(t) ** k for k in range(5)) / mp.log(1 + mp.mpf(t), 2) - 1) for t in [rmax * (2 * i / 2000 - 1) for i in range(2001)] if t != 0)
e4 = max(abs((1 + mp.mpf(t) * sum(C2[k] * mp.mpf(t) ** k for k in range(3))) / mp.power(2, mp.mpf(t)) - 1) for t in [1 / 64 * (2 * i / 2000 - 1) for i in range(2001)])
print(f"POWF_LOW: log2 degree 4 rel err 2^{float(mp.log(e3, 2)):.1f}, exp2 degree 2 rel err 2^{float(mp.log(e4, 2)):.1f}")
