"""gen-erfd-tables.py: the tables of tierd-erf.c (2026-10-01), written to
erfd-tables.h (generated: do not edit). For r = k/128:
  ERFD_ROWS[k] = {erf(r), S(r)}, k = 0..768 (r <= 6; erf rounds to 1 in
    double from 5.9216 on);
  ERFCD_ROWS[k] = {erfc(r), S(r)} times 2^128, k = 0..3488 (r <= 27.25;
    erfc is below 2^-1075 from 27.2264 on), the scale keeping the tail's
    rows out of the subnormal range;
S(r) = 2/sqrt(pi) exp(-r^2); each entry the double nearest, from mpmath at
300 bits."""
import mpmath as mp
mp.mp.prec = 300
NK, NKC = 769, 3489
SC = mp.mpf(2) ** 128
def S(r): return 2 / mp.sqrt(mp.pi) * mp.exp(-r * r)
def lit(v):
    return float(v).hex() if v != 0 else "0x0p+0"
out = ["/* erfd-tables.h: generated by gen-erfd-tables.py -- do not edit. At r = k/128, S = 2/sqrt(pi) exp(-r^2):",
       "   ERFD_ROWS[k] = {erf, S}; ERFCD_ROWS[k] = {erfc, S} times 2^128. */",
       f"#define ERFD_NK {NK}", f"#define ERFCD_NK {NKC}",
       "static const double ERFD_ROWS[ERFD_NK][2] __attribute__((aligned(16))) = {"]
for k in range(NK):
    r = mp.mpf(k) / 128
    out.append("  {" + lit(mp.erf(r)) + ", " + lit(S(r)) + "},")
out.append("};")
out.append("static const double ERFCD_ROWS[ERFCD_NK][2] __attribute__((aligned(16))) = {")
for k in range(NKC):
    r = mp.mpf(k) / 128
    out.append("  {" + lit(mp.erfc(r) * SC) + ", " + lit(S(r) * SC) + "},")
out.append("};")
open("erfd-tables.h", "w").write("\n".join(out) + "\n")
print("wrote erfd-tables.h,", NK, "+", NKC, "rows")
