"""gen-powd-tables.py: the log tables of tierd-pow.c (2026-10-01), written to
powd-tables.h (generated: do not edit). glibc pow's log (pow_log_data.c's
recipe, rebuilt here): tmp = ix - OFF, OFF = 0x3fe6955500000000, i = bits
51-45 of tmp, z = x scaled into [OFF, 2 OFF). Subinterval i is z in
[OFF + i 2^45, OFF + (i+1) 2^45) as bit patterns, centre m_i; then
  invc = round(128/m)/128 (m < 1) or round(256/m)/256 (m >= 1): few bits,
    so r = z invc - 1 is exact by one FMA;
  logc = log(1/invc) rounded to a multiple of 2^-43 (k L1 + logc is then
    exact for |k| < 2^10, L1 = glibc's Ln2hi), logctail = the rest;
the subinterval holding 1 gets invc = 1, logc = 0. And B1..B6 with
log1p(r) = r - r^2/2 + r^3 (B1 + B2 r + ... + B6 r^5) on the largest |r|
(least squares on Chebyshev nodes, absolute error, coefficients rounded to
double), its error printed."""
import mpmath as mp, struct
mp.mp.prec = 300
OFF = 0x3fe6955500000000
N = 128
def dbl(bits): return struct.unpack("<d", struct.pack("<Q", bits))[0]
def bits(d): return struct.unpack("<Q", struct.pack("<d", d))[0]
inv, lc, lt = [], [], []
rmax = mp.mpf(0)
for i in range(N):
    a = dbl(OFF + (i << 45)); b = dbl(OFF + ((i + 1) << 45))
    m = (mp.mpf(a) + mp.mpf(b)) / 2
    ic = (mp.nint(N / m) / N) if m < 1 else (mp.nint(2 * N / m) / (2 * N))
    L = -mp.log(ic)
    logc = mp.nint(L * mp.mpf(2) ** 43) / mp.mpf(2) ** 43
    inv.append(float(ic)); lc.append(float(logc)); lt.append(float(L - logc))
    assert mp.mpf(float(ic)) == ic and mp.mpf(float(logc)) == logc
    for z in (a, b):
        rmax = max(rmax, abs(mp.mpf(z) * ic - 1))
one = [i for i in range(N) if inv[i] == 1.0]
# the fit: q(r) = (log1p(r) - r + r^2/2)/r^3, absolute error of r^3 q
deg = 5; NN = 300; R = rmax * mp.mpf("1.001")
nodes = [R * mp.cos(mp.pi * (k + mp.mpf(1) / 2) / NN) for k in range(NN)]
A = mp.matrix(NN, deg + 1); y = mp.matrix(NN, 1)
for n, t in enumerate(nodes):
    w = t ** 3
    for k in range(deg + 1): A[n, k] = w * t ** k
    y[n] = mp.log1p(t) - t + t * t / 2
c = mp.lu_solve(A.T * A, A.T * y)
B = [float(c[k]) for k in range(deg + 1)]
worst = 0
for n in range(-2000, 2001):
    t = R * n / 2000
    if t == 0: continue
    q = mp.mpf(0)
    for k in reversed(range(deg + 1)): q = q * t + mp.mpf(B[k])
    worst = max(worst, abs(t ** 3 * q - (mp.log1p(t) - t + t * t / 2)))
lit = lambda v: float(v).hex() if v != 0 else "0x0p+0"
out = ["/* powd-tables.h: generated by gen-powd-tables.py -- do not edit. glibc pow's log tables (pow_log_data.c's",
       f"   recipe); |r| <= {float(rmax):.6g}; the polynomial's absolute error 2^{float(mp.log(worst, 2)):.1f}. */",
       f"#define POWD_ONE {one[0]}   /* the subinterval holding 1 */",
       "static const double POWD_INVC[128] = {" + ", ".join(lit(v) for v in inv) + "};",
       "static const double POWD_LOGC[128] = {" + ", ".join(lit(v) for v in lc) + "};",
       "static const double POWD_LOGCT[128] = {" + ", ".join(lit(v) for v in lt) + "};",
       "static const double POWD_B[6] = {" + ", ".join(lit(v) for v in B) + "};",
       "#define POWD_L1 0x1.62e42fefa3800p-1", "#define POWD_L2 0x1.ef35793c76730p-45"]
open("powd-tables.h", "w").write("\n".join(out) + "\n")
print("wrote powd-tables.h; one at", one, "; |r| <=", float(rmax), "; poly abs err 2^%.1f" % float(mp.log(worst, 2)))
