"""gen-erfc-tables.py: the table of tier-erfcf.c (2026-10-01), written to
erfc-tables.h (generated: do not edit). For r = k/128, k = 0..NK-1:
erfc(r) and S(r) = 2/sqrt(pi) exp(-r^2) as float pairs, from mpmath at 200
bits. NK covers r up to 8.5 + 1/128: beyond, S's low part is subnormal."""
import mpmath as mp
import numpy as np
mp.mp.prec = 200
NK = 1090
f32 = lambda v: float(np.float32(float(v)))
def lit(v):
    if v == 0: return "0x0p+0f"
    m, e = float(v).hex().split("p")
    return f"{m.rstrip('0').rstrip('.')}p{e}f"
out = ["/* erfc-tables.h: generated by gen-erfc-tables.py -- do not edit. ERFC_ROWS[k] = {erfc hi, erfc lo, S hi, S lo}",
       "   at r = k/128, S = 2/sqrt(pi) exp(-r^2). */",
       f"#define ERFC_NK {NK}",
       "static const float ERFC_ROWS[ERFC_NK][4] __attribute__((aligned(16))) = {"]
for k in range(NK):
    r = mp.mpf(k) / 128
    E = mp.erfc(r); S = 2 / mp.sqrt(mp.pi) * mp.exp(-r * r)
    eh = f32(E); el = f32(E - mp.mpf(eh)); sh = f32(S); sl = f32(S - mp.mpf(sh))
    out.append("  {" + ", ".join(lit(v) for v in (eh, el, sh, sl)) + "},")
out.append("};")
open("erfc-tables.h", "w").write("\n".join(out) + "\n")
print("wrote erfc-tables.h,", NK, "rows")
